### ISSUE TITLE
A question about the fast sweeping part

### ISSUE THREAD

**Issue by xmeng525** [christopherbatty/SDFGen#12]
Hi Prof. Batty,
Thank you for the great implementation! I have a question about the [fast sweeping part](https://github.com/christopherbatty/SDFGen/blob/4b6fa27dd7ea729c40665356ec5d5c4be230b89a/makelevelset3.cpp#L163).
According to Section 2.2 in [A fast sweeping method for eikonal equations] (https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=zwBJ5LAAAAAJ&citation_for_view=zwBJ5LAAAAAJ:d1gkVwhDpl0C), for a 3D grid, we should get the correct SDF result by sweeping 8 times from the 8 different directions.
However, in Line 163, the number of passes is two, which means that there are 16 sweeps in total.

I tried to change the number of pass to 1 (i.e. sweeping 8 times). And it did give the WRONG SDF result.
Would you please briefly explain why we need two passes?
Thank you.

Best regards,
Xiaoxu Meng

**Comment by christopherbatty** [comment]
Hi Xiaoxu,
I didn't write the actual mesh-to-levelset conversion code itself (just the wrapper around it), so I would need to investigate more deeply to answer your question, and unfortunately do not have time at the moment. 
However, I will note that the algorithm implemented here is somewhat different from what is done in the paper you link. In the paper, the update to an unknown value based on its known neighbouring grid points is computed by solving their equation (2.3) via (2.4), I believe, similar also to traditional fast marching methods. By contrast, in this code, the information being propagated during the sweeps is actually the index of the closest triangle (from which an exact point-to-tri distance is then calculated and used). There are likely other differences as well. As a result, it's not clear to me that you should necessarily expect the discussions in that paper to be able to be applied verbatim to this code.

**Comment by xmeng525** [comment]
Hi Prof. Batty,
Thank you for your reply!
The difference you noticed is inspiring. I'll try to check it out.
Best regards,
Xiaoxu
