### ISSUE TITLE
Sign only reliable for watertight meshes?

### ISSUE THREAD

**Issue by davidstutz** [christopherbatty/SDFGen#4]
Hi,

as in Robert Bradson's code, I assume that the inside/outside test only works for (more or less) watertight meshes, right? I am specifically referring to [line 173](https://github.com/christopherbatty/SDFGen/blob/master/makelevelset3.cpp#L173) in the code.

Thanks!

**Comment by christopherbatty** [comment]
That's right. If the mesh is not watertight, then inside/outside is ill-defined, so you won't likely get a consistent/meaningful result.

**Comment by davidstutz** [comment]
Thanks for the clarification!
