### ISSUE TITLE
OBJ to SDF Conversion Loses Resolution

### ISSUE THREAD

**Issue by 3dfoster** [christopherbatty/SDFGen#5]
In converting an obj file to sdf I lose almost all resolution/detail from the previous obj file.  

Here is the input file:
![cave](https://user-images.githubusercontent.com/13704150/44284183-93a6df80-a215-11e8-8368-696feaa4220f.png)

And here is the sdf file generated:
![sdf_cave](https://user-images.githubusercontent.com/13704150/44284186-97d2fd00-a215-11e8-9351-ac8e1c6c9dbc.png)

When running the command I use `.03` for dx and `5` for padding.

Any insight as to how I can get more accurate results would be greatly appreciated.

**Comment by 3dfoster** [comment]
We discovered the issue it was on our end.

**Comment by zenghuilipete** [comment]
@fasterthan Can you clarify what is your solution to fix this issue? I meet the same question as you, the output from SDFGen lose all details. Another question, how to verify the output from SDFGen is right or not? Any tool can show the result? Thank you!

**Comment by zzxmllq** [comment]
@zenghuilipete hi，did you solve this problem？How to show the result？Thanks！

**Comment by 3dfoster** [comment]
> @fasterthan Can you clarify what is your solution to fix this issue? I meet the same question as you, the output from SDFGen lose all details. Another question, how to verify the output from SDFGen is right or not? Any tool can show the result? Thank you!

There was nothing wrong with SDGen's output file in our case, it was a bug in our own program that lost detail.
