### ISSUE TITLE
How to go from particle to mesh surface?

### ISSUE THREAD

**Issue by uljad** [christopherbatty/SDFGen#8]
I am interested in knowing how to convert particle position to levelsets? The documentation is a little unclear, how can I do what the  paper: [https://cs.uwaterloo.ca/~c2batty/papers/BattyBridson08.pdf](url) shows? Main goal is to be able to make buckling analysis of the fallen fluid.

**Comment by christopherbatty** [comment]
This tool does not provide the functionality to convert from particles to meshes. It is designed only to convert a mesh into a grid-based signed distance field.
It sounds like what you are looking for is a marching cubes or marching tets implementation.
